FROM debian:jessie
LABEL maintainer louie.liu@westernasset.com

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y unzip ca-certificates sed curl && \
    update-ca-certificates && \
    rm -r /var/lib/apt/lists/*

ENV CONSUL_TEMPLATE_VERSION 0.19.5
ADD https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip /tmp/consul-template.zip

RUN unzip /tmp/consul-template.zip -d /usr/bin && \
    chmod +x /usr/bin/consul-template && \
    rm /tmp/consul-template.zip


# Install Vault
ENV VAULT_VERSION 0.11.1
ADD https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip /tmp/vault.zip

RUN unzip /tmp/vault.zip -d /usr/bin && \
    chmod +x /usr/bin/vault && \
    rm /tmp/vault.zip

RUN mkdir -p /opt/resources/liquibase
COPY resources/wam_liquibase.ctmpl /opt/resources/liquibase/

RUN chown -R jenkins:jenkins /opt/resources

USER jenkins
