FROM alpine:latest AS get-env

ADD https://downloads.sourceforge.net/project/mussh/mussh/1.0/mussh-1.0.tgz mussh-1.0.tgz
RUN tar zxvf mussh-1.0.tgz mussh/mussh

FROM alpine:latest
RUN apk add --no-cache bash openssh
COPY config /root/.ssh/config
COPY --from=get-env mussh/mussh /usr/local/bin/mussh

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

USER jenkins
