FROM openjdk:11.0.8-jdk
LABEL maintainer louie.liu@westernasset.com

ARG user=jenkins
ARG group=jenkins
ARG CONSUL_TEMPLATE_VERSION=0.19.4
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

# Run time variables
ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}
ENV TZ='America/Los_Angeles'

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y dateutils apt-utils
RUN apt-get install -y --no-install-recommends jq
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN wget -q -O /tmp/liquibase.tar.gz "https://github.com/liquibase/liquibase/releases/download/v4.3.1/liquibase-4.3.1.tar.gz"
RUN mkdir -p /opt/resources/liquibase
RUN tar -xzf /tmp/liquibase.tar.gz -C /opt/resources/liquibase
RUN rm -f /tmp/liquibase.tar.gz
RUN chmod +x /opt/resources/liquibase/liquibase
RUN ln -s /opt/resources/liquibase/liquibase /usr/local/bin/

RUN cd /opt/resources/liquibase/lib \
    && curl -O https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.0/snowflake-jdbc-3.13.0.jar

RUN cd /opt/resources/liquibase/lib \
    && curl -O https://github.com/liquibase/liquibase-snowflake/releases/download/liquibase-snowflake-4.3.1/liquibase-snowflake-4.3.1.jar

COPY wam_liquibase.ctmpl /opt/resources/liquibase/

RUN chown -R jenkins:jenkins /opt/resources

USER jenkins
