FROM python:3.7-buster
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y apt-utils curl jq
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install Vault
ENV VAULT_VERSION 1.4.1
ADD https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip /tmp/vault.zip

RUN unzip /tmp/vault.zip -d /usr/bin && \
    chmod +x /usr/bin/vault && \
    rm /tmp/vault.zip

# Installing Virtualenv Since can be a shared container
RUN pip install virtualenv --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
# Installing common dependencies
RUN pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org requests
	
USER jenkins
