FROM centos:7

# Project - Template
# Runs Python 2 and Python 3 using virtualenv.

# Var
ENV PYTHON_2_VERSION 2.7.16
ENV PYTHON_3_VERSION 3.7.3

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Updating Container
RUN yum -y update

# Installing tools to compile Python
RUN yum groupinstall -y "development tools"
RUN yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel
RUN yum install -y db4-devel libpcap-devel xz-devel expat-devel libffi-devel gcc
RUN yum install -y wget which

# Installing Python 2
RUN cd /usr/src && \
    wget -O python.tar.tgz "https://www.python.org/ftp/python/${PYTHON_2_VERSION%%[a-z]*}/Python-${PYTHON_2_VERSION}.tgz" && \
   tar xzf python.tar.tgz && \
   cd Python-${PYTHON_2_VERSION} && \
   ./configure --enable-optimizations && \
   make install

# Update Pip for python 2
RUN cd /usr/src && \
   wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py --no-check-certificate && \
    python get-pip.py --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org

# Installing Python 3
RUN cd /usr/src && \
    wget -O python.tar.tgz "https://www.python.org/ftp/python/${PYTHON_3_VERSION%%[a-z]*}/Python-${PYTHON_3_VERSION}.tgz" && \
   tar xzf python.tar.tgz && \
   cd Python-${PYTHON_3_VERSION} && \
   ./configure --enable-optimizations && \
   make install

# Update Pip for python 3
RUN cd /usr/src && \
   wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py --no-check-certificate && \
    python get-pip.py --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org

# Installing Virtualenv Since can be a shared container
RUN pip install virtualenv --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN python3 -m pip install virtualenv --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org

# Installing Cookiecutter
RUN pip install cookiecutter --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN python3 -m pip install cookiecutter --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
