FROM node:8.11.3

ARG user=jenkins
ARG group=jenkins
ARG uid=10000
ARG gid=10000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Angular CLI
RUN npm install -g @angular/cli
