FROM openjdk:11.0.12-jdk
LABEL maintainer louie.liu@westernasset.com

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

ARG MAVEN_VERSION=3.8.2
ARG USER_HOME_DIR="/home/jenkins"
ARG SHA=b0bf39460348b2d8eae1c861ced6c3e8a077b6e761fb3d4669be5de09490521a74db294cf031b0775b2dfcd57bd82246e42ce10904063ef8e3806222e686f222
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

# Run time variables
ENV TZ='America/Los_Angeles'

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y dateutils
RUN apt-get install -y --no-install-recommends jq
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get install -y --no-install-recommends ruby
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

USER jenkins
