FROM openjdk:8u151
LABEL maintainer louie.liu@westernasset.com

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG MAVEN_VERSION=3.5.2
ARG USER_HOME_DIR=/home/${user}
ARG SHA=707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN mkdir -p /usr/share/maven /usr/share/maven/ref
RUN curl -fsSLk -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz
RUN echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c -
RUN tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1
RUN rm -f /tmp/apache-maven.tar.gz
RUN ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# Run time variables
ENV TZ='America/Los_Angeles'

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y dateutils
RUN apt-get install -y --no-install-recommends jq
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
