FROM python:2.7
MAINTAINER "WAM DEVOPS <devops cop@westernasset.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends gcc python-dev libkrb5-dev
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install pywinrm
RUN pip install pywinrm[kerberos]

COPY resources/krb5.conf /etc/

ENV HOME /home/jenkins
RUN groupadd -g ${gid} ${group}
RUN useradd -d "/home/jenkins" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
