FROM python:3.6
MAINTAINER "WAM DEVOPS <devops cop@westernasset.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install orionsdk

ENV HOME /home/jenkins
RUN groupadd -g ${gid} ${group}
RUN useradd -d "/home/jenkins" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
