FROM ubuntu:18.04

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV HOME /home/jenkins
RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN apt-get install -y libaio1 curl unzip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://get.pulumi.com | sh
RUN cp ~/.pulumi/bin/* /usr/bin/

USER jenkins
