FROM openjdk:8
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

# Env variables
ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}
ENV PATH="/opt/tableau/tabcmd/bin:${PATH}"

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apt-get update
RUN apt-get install -y gdebi bash-completion
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN cd /opt && curl -O https://downloads.tableau.com/esdalt/2018.3.11/tableau-tabcmd-2018-3-11_all.deb && ls -la /opt
RUN gdebi -n /opt/tableau-tabcmd-2018-3-11_all.deb

COPY conf/db.ctmpl /opt/db.ctmpl
RUN chown jenkins:jenkins /opt/db.ctmpl

USER jenkins
