FROM python:3.7.9-stretch

#### JENKINS REQUIREMENTS

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

COPY src/* /opt/
COPY conf/db.ctmpl /opt/db.ctmpl
RUN chown -R jenkins:jenkins /opt

RUN python3 -m pip install PyGithub==1.51 --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN python3 -m pip install PyYAML==5.3.1 --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN python3 -m pip install setuptools==40.8.0 --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN python3 -m pip install tableauserverclient==0.10 --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org
