FROM node:12.18.3-buster
LABEL maintainer="devops@westernasset.com"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=node
ARG uid=1000
ARG gid=1000
ARG home=/home/${user}

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN usermod -u 1001 node
RUN useradd -d "${home}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apt-get update
RUN apt-get install -y git jq unzip gcc groff less openssh-server
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
RUN mv /tmp/eksctl /usr/local/bin

RUN curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/aws-iam-authenticator
RUN curl -o aws-iam-authenticator.sha256 https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/aws-iam-authenticator.sha256
RUN openssl sha1 -sha256 aws-iam-authenticator
RUN chmod +x ./aws-iam-authenticator
RUN cp ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
RUN kubectl version --client

USER jenkins
