FROM alpine:3.6
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

ENV AWSCLI_VERSION "1.16.116"

RUN apk -v --update add \
        ca-certificates \
        jq \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli==${AWSCLI_VERSION} && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*
