FROM node:alpine
LABEL maintainer="devops@westernasset.com"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=node
ARG home=/home/${user}
ARG uid=1000

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git shadow

RUN usermod -u 1001 node
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git shadow

ENV AWSCLI_VERSION "1.16.260"
ENV AWSCDK_VERSION 1.13.0

RUN npm config set unsafe-perm true

#pip3 needs to be run initialy to upgrade pip
RUN pip3 install --upgrade pip
RUN pip install boto3 \
  json-spec \
  yamllint

RUN pip install awscli==${AWSCLI_VERSION}

RUN npm install -g aws-cdk@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-amazonmq@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-apigateway@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-autoscaling@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-batch@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudformation@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudfront@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudwatch@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-ec2@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-efs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-ecs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-elasticloadbalancingv2@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-events@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-iam@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-transfer@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-s3@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-sns@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-sqs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-lambda@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-lambda-event-sources@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-logs@${AWSCDK_VERSION}
RUN npm install typescript@latest
RUN npm install @types/node@latest

RUN apk -v --update add \
        ca-certificates \
        jq \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli==${AWSCLI_VERSION} && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*

USER jenkins
