FROM node:alpine
LABEL maintainer="devops@westernasset.com"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=node
ARG home=/home/${user}
ARG uid=1000

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git shadow jq

RUN usermod -u 1001 node
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git shadow

ENV AWSCLI_VERSION "1.16.260"
ENV AWSCDK_VERSION 1.32.2

RUN npm config set unsafe-perm true

#pip3 needs to be run initialy to upgrade pip
RUN pip3 install --upgrade pip
RUN pip install boto3 \
  json-spec \
  yamllint

RUN pip install awscli==${AWSCLI_VERSION}

RUN npm install -g aws-cdk@${AWSCDK_VERSION}
RUN npm install typescript@latest
RUN npm install @types/node@latest

RUN apk -v --update add \
        ca-certificates \
        jq \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli==${AWSCLI_VERSION} && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*

USER jenkins
