FROM ubuntu:16.04
MAINTAINER "Steven Tobias (Red8) <stobias@red8.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV PACKER_VERSION=1.2.3
ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}
ENV PATH="/usr/lib/vmware/bin:${PATH}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends  dateutils \
                                                apt-utils \
                                                git \
                                                bash \
                                                openssh-server \
                                                curl \
                                                unzip \
                                                sudo \
                                                dateutils \
                                                apt-utils \
                                                python3 \
                                                python3-pip \
                                                python-setuptools

## Python ansible dependencies. We can push this into multistage if needed.
COPY files/requirements.txt .
#RUN pip3 install --upgrade pip3
#RUN pip3 install -r requirements.txt
