FROM node:10.16.0
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN usermod -u 1001 node

RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Angular CLI
RUN npm install -g @angular/cli@8.3.5

USER jenkins
