FROM alpine:3.9
LABEL maintainer="DevOps <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

RUN apk update && \
  apk upgrade && \
  apk add --no-cache ca-certificates && \
  apk add openssh-client && \
  apk add curl && \
  apk add git && \
  rm -rf /var/cache/apk/*

# Set helm & rke version
ENV HELM_VERSION="v2.12.3" \
  KUBE_VERSION="v1.13.2"

RUN curl -Lk -o /usr/local/bin/kubectl \
  https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl && \
  chmod +x /usr/local/bin/kubectl

RUN curl -k https://kubernetes-helm.storage.googleapis.com/helm-${HELM_VERSION}-linux-amd64.tar.gz \
  | tar xvz --strip-components=1 linux-amd64/helm && \
  mv -f helm /usr/local/bin/helm
