FROM alpine:3.8
LABEL maintainer="DevOps <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

RUN apk update && \
  apk upgrade && \
  apk add --no-cache ca-certificates && \
  apk add openssh-client && \
  apk add iputils && \
  apk add iproute2 && \
  apk add curl && \
  apk add git && \
  apk add bash && \
  apk add --quiet --no-cache --virtual build-dependencies curl && \
  apk del build-dependencies && \
  rm -rf /var/cache/apk/*

# Define rancher version
ENV RANCHER_VERSION=v0.6.13 \
  RKE_VERSION="v0.1.15" \
  YAML_VERSION=1.6 \
  RANCHER_URL= \
  RANCHER_ACCESS_KEY= \
  RANCHER_SECRET_KEY= \
  RANCHER_ENVIRONMENT=

RUN curl -fsSLOk https://github.com/rancher/cli/releases/download/${RANCHER_VERSION}/rancher-linux-amd64-${RANCHER_VERSION}.tar.gz && \
  tar --strip-components=2 -xzvf rancher-linux-amd64-${RANCHER_VERSION}.tar.gz -C /usr/local/bin && \
  chmod +x /usr/local/bin/rancher && \
  rm -f rancher-linux-amd64-${RANCHER_VERSION}.tar.gz

RUN curl -Lk -o /usr/local/bin/rke \
  https://github.com/rancher/rke/releases/download/${RKE_VERSION}/rke_linux-amd64 && \
  chmod 755 /usr/local/bin/rke
