FROM python:3.8-buster

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV HOME /home/jenkins
RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Build Dependencies Python 3
RUN python -m pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org setuptools
RUN python -m pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org wheel
RUN python -m pip install --upgrade --trusted-host pypi.org --trusted-host files.pythonhosted.org twine
