FROM imagehub.westernasset.com/docker/devops/jenkins-builder:julia-1.5.3

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        libpython3.7=3.7.3-* \
        python3.7=3.7.3-* \
        python3-pip=18.1-* \
        python3-setuptools=40.8.0-* \
        python3-wheel=0.32.3-* \
 && rm -rf /var/lib/apt/lists/*
 