FROM alpine:3.8

RUN	apk --update add \
		bash \
		ca-certificates \
		git \
		less \
		openssl \
		openssh-client \
		p7zip \
		python \
		py-lxml \
		py-pip \
		rsync \
		sshpass \
		sudo \
		subversion \
		vim \
		zip \
		krb5 \
			&& apk --update add --virtual \
		build-dependencies \
		python-dev \
    krb5-dev \
		musl-dev \
		gcc \
		libffi-dev \
		openssl-dev \
		build-base \
	&& pip install --upgrade \
		pip \
		cffi \
	&& pip install \
		ansible==2.6.3  \
		ansible-lint==3.4.23 \
		awscli==1.15.83 \
		boto==2.49.0 \
 		boto3==1.7.82 \
		docker-py==1.10.6 \
		dopy==0.3.7 \
		python_jenkins==1.1.0 \
		pywinrm==0.3.0 \
		pywinrm[kerberos] \
		pywinrm[credssp] \
		pyvmomi \
		pysphere \
	&& apk del build-dependencies \
	&& rm -rf /var/cache/apk/*

RUN	mkdir -p /etc/ansible \
	&& echo 'localhost' > /etc/ansible/hosts \
	&& mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

COPY resources/krb.conf /etc/krb5.conf

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h /home/${user} -s /bin/bash -D ${user}

USER ${user}
WORKDIR ${home}
RUN mkdir ~/.ssh \
  && echo 'StrictHostKeyChecking no'>${home}/.ssh/config

ONBUILD	WORKDIR	/tmp
ONBUILD	COPY . /tmp
ONBUILD	RUN ansible -c local -m setup all > /dev/null
CMD ["bash"]
