FROM pasdtr.westernasset.com/risk/julia:julia-1.0.2

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
