FROM jenkinsci/jnlp-slave:4.0.1-1
LABEL maintainer louie.liu@westernasset.com

USER root

# Install Build dependencies
RUN apt-get update \
 && apt-get install -y --no-install-recommends jq unzip curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER jenkins
