FROM python:3.8.12-buster
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG uid=1000
ARG gid=1000
ARG home=/home/${user}

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN groupadd -g ${gid} jenkins
RUN useradd -d "${home}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apt-get update
RUN apt-get install -y python3-dev git gcc musl-dev curl unzip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN pip install botocore==1.23.33 --upgrade
RUN pip install aws-sam-cli==1.37.0 --upgrade

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

USER jenkins
