FROM node:alpine

LABEL maintainer="devops@westernasset.com"

ENV AWSCDK_VERSION 1.0.0

RUN npm config set unsafe-perm true

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git

#pip3 needs to be run initialy to upgrade pip
RUN pip3 install --upgrade pip
RUN pip install boto3 \
  json-spec \
  yamllint

RUN pip install awscli --upgrade

RUN npm install -g aws-cdk@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-amazonmq@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-apigateway@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-autoscaling@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-batch@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudformation@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudfront@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-cloudwatch@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-ec2@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-efs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-ecs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-elasticloadbalancingv2@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-events@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-iam@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-s3@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-sns@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-sqs@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-lambda@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-lambda-event-sources@${AWSCDK_VERSION}
RUN npm install @aws-cdk/aws-logs@${AWSCDK_VERSION}
RUN npm install typescript@latest
RUN npm install @types/node@latest
