FROM python:3.8.2-alpine
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG home=/home/${user}
ARG uid=1000

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN addgroup ${group}
RUN adduser -G ${group} -u ${uid} -g "Jenkins User" -h ${home} -s /bin/bash -D ${user}

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
  python3 python3-dev git gcc musl-dev curl unzip

RUN pip install botocore==1.23.29 --upgrade
RUN pip install awscli==1.22.32 --upgrade
RUN pip install aws-sam-cli==1.29.0 --upgrade

USER jenkins
