FROM ubuntu:18.04
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN pip3 install awscli --upgrade
RUN pip3 install aws-sam-cli

RUN ln -s /usr/bin/python3 /usr/bin/python
