FROM python:3.7.4-stretch
LABEL maintainer="WAM DEVOPS <devops@westernasset.com>"

# Create the jenkins user & group.
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN pip install awscli==1.18.34 --upgrade
RUN pip install aws-sam-cli==0.47.0 --upgrade

USER jenkins
