FROM ubuntu:18.04

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV HOME /home/jenkins
RUN groupadd -g ${gid} ${group}
RUN useradd -d "${USER_HOME_DIR}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN apt-get install -y libaio1 curl unzip git
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

ENV HELM_VERSION 3.4.0
ADD https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz /helm-v${HELM_VERSION}-linux-amd64.tar.gz

RUN tar -zxvf /helm-v${HELM_VERSION}-linux-amd64.tar.gz
RUN mv /linux-amd64/helm /usr/local/bin/helm

RUN helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.2

USER jenkins
