
FROM openjdk:8u151
LABEL maintainer louie.liu@westernasset.com

ARG user=jenkins
ARG group=jenkins
ARG CONSUL_TEMPLATE_VERSION=0.19.4
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

# Run time variables
ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}
ENV SONAR_SCANNER_VERSION 3.3.0.1492
ENV TZ='America/Los_Angeles'

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

# Install Build dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install Consul-template
RUN cd /opt \
 && curl -O  http://artifactory.westernasset.com/artifactory/third-party-releases-local/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip \
 && unzip sonar-scanner-${SONAR_SCANNER_VERSION}-linux.zip

RUN mv /opt/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux /opt/sonarscanner

COPY conf/sonar-scanner.properties /opt/sonarscanner/conf/sonar-scanner.properties
