FROM clojure:openjdk-8-lein-2.9.1-stretch
LABEL maintainer="Kevin Yen <Kevin.Yen@westernasset.com>"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG USER_HOME_DIR=/home/${user}

ENV JENKINS_AGENT_HOME ${USER_HOME_DIR}

RUN groupadd -g ${gid} ${group}
RUN useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

WORKDIR /home/jenkins

USER jenkins
